name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        channel: [master, stable]
      # Disable fail-fast; we want results from all channels even if one fails.
      fail-fast: false

    steps:
    - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      with:
        path: charts
    - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      with:
        path: flutter
        repository: flutter/flutter
        ref: ${{ matrix.channel }}
        # Shallow clones don't work; see https://github.com/flutter/flutter/issues/18532
        fetch-depth: 0
    - name: Add Flutter tags
      # Add tags, which are also necessary for version checks to work.
      run: git fetch origin +refs/tags/*:refs/tags/*
      working-directory: ${{ github.workspace }}/flutter
    - name: Add Flutter to path
      run: echo "$GITHUB_WORKSPACE/flutter/bin" >> $GITHUB_PATH
    - name: Doctor
      # Run doctor, for ease of debugging any issues.
      run: flutter doctor -v
    - name: charts_common tests
      run: |
        dart pub get
        dart pub run test
      working-directory: ${{ github.workspace }}/charts/charts_common
    - name: charts_flutter tests
      run: flutter test
      working-directory: ${{ github.workspace }}/charts/charts_flutter

